---

- name: ca intermediate dir
  ansible.builtin.file:
    path: "{{ ca_intermediate_dir }}"
    state: directory

- name: ca intermediate 'private' dir
  ansible.builtin.file:
    path: "{{ ca_intermediate_dir }}/private"
    state: directory

- name: CA Intermediate Private Key
  community.crypto.openssl_privatekey:
    path: "{{ ca_intermediate_dir }}/private/intermediate-ca.key.pem"
    passphrase: "{{ ca_intermediate_passphrase }}"
    cipher: aes256
  register: ca_intermediate_key

- name: CA Intermediate CSR
  openssl_csr:
    path: "{{ ca_intermediate_dir }}/intermediate-ca.csr"
    common_name: "my-intermediate-ca"
    privatekey_path: "{{ ca_intermediate_key.filename }}"
    privatekey_passphrase: "{{ ca_intermediate_passphrase }}"
  register: ca_intermediate_csr

- name: CA Intermediate sign CSR
  community.crypto.x509_certificate:
    path: "{{ ca_intermediate_dir }}/intermediate-ca.crt"
    csr_path: "{{ ca_intermediate_csr.filename }}"
    provider: selfsigned
    privatekey_path: "{{ ca_root_key.filename }}"
    privatekey_passphrase: "{{ ca_root_passphrase }}"
  register: ca_root_crt
