---

- name: Pre Req Tasks
  hosts: all
  tasks:

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 1

    - name: Pre Req Tasks
      include_tasks: tasks/prereqs.yaml

- name: CA Root
  hosts: all
  tasks:

    - name: CA Root Tasks
      include_tasks: tasks/ca_root.yaml

- name: CA Intermediate
  hosts: all
  tasks:

    - name: CA Intermediate Tasks
      include_tasks: tasks/ca_intermediate.yaml

- name: CA Intermediate Chain
  hosts: all
  vars:
    ca_certs:
      - "{{ ca_root_cert_file }}"
      - "{{ ca_intermediate_cert_file }}"
  tasks:

    - name: CA Intermediate Chain read files
      command: awk 1 {{ ca_certs | join(' ') }}
      register: ca_certs_contents

    - name: CA Intermediate Chain create merged file
      copy:
        dest: "{{ ca_intermediate_dir }}/chain-ca.pem"
        content: "{{ ca_certs_contents.stdout_lines | join('\n') }}"
