---

- name: Pre Req Tasks
  hosts: all
  tasks:

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 1

    - name: Pre Req Tasks
      include_tasks: tasks/prereqs.yaml

- name: CA Root
  hosts: all
  tasks:

    - name: CA Root Tasks
      include_tasks: tasks/ca_root.yaml

- name: CA Intermediate
  hosts: all
  tasks:

    - name: CA Intermediate Tasks
      include_tasks: tasks/ca_intermediate.yaml
